### ISSUE TITLE
suggest going back to full height sections on desktop

### ISSUE THREAD

**Issue by ferndopolis** [jackpine/jackpine.github.com#24]
@michaelkirk i know you had some good reasons why you chose to remove the full height sections except the main section.  but now when viewed on a large desktop it makes the site section look too short and lacking content.   

![screen shot 2015-01-09 at 9 06 19 am](https://cloud.githubusercontent.com/assets/764493/5683715/057da80e-97df-11e4-9069-0d4f5e4f9a7f.png)

**Comment by michaelkirk** [comment]
@ferndopolis yeah, you are right. Good catch. I'm still a bit hesitant to go back to fullscreen slides because they lack some flexibility. Would you be satisfied by a max-width so that there are always at least 2 rows of heads? 

e.g. we'd make it look like this:
![screen shot 2015-01-18 at 8 38 27 pm](https://cloud.githubusercontent.com/assets/217057/5796020/01ed3a5e-9f52-11e4-8fe7-a05114033729.png)

Instead of this:
![screen shot 2015-01-18 at 8 40 19 pm](https://cloud.githubusercontent.com/assets/217057/5796029/39d89184-9f52-11e4-961d-654295051a46.png)

**Comment by michaelkirk** [comment]
Any opinion @j-j-liebsch ?

**Comment by ferndopolis** [comment]
@michaelkirk yeah max width looks better.

**Comment by michaelkirk** [comment]
solved with 10e40eba6cec896bb176bc450e55cc3b5597e8c5
